# Generated by Django 3.1.4 on 2020-12-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolanswer',
            old_name='id',
            new_name='answer_id',
        ),
        migrations.RenameField(
            model_name='mcqanswer',
            old_name='id',
            new_name='answer_id',
        ),
        migrations.RenameField(
            model_name='textanswer',
            old_name='id',
            new_name='answer_id',
        ),
    ]
