# Generated by Django 3.1.4 on 2020-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_auto_20201230_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='textform',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='textform',
            name='user_id',
        ),
    ]
