# Generated by Django 3.1.4 on 2020-12-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0003_auto_20201230_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textanswer',
            name='user_id',
        ),
    ]
