# Generated by Django 3.1.4 on 2021-01-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0008_auto_20201231_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqanswer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='mcqform',
            name='user_id',
        ),
    ]
