# Generated by Django 3.1.4 on 2021-01-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0009_auto_20210101_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boolform',
            name='option',
        ),
        migrations.RemoveField(
            model_name='boolform',
            name='user_id',
        ),
    ]
