# Generated by Django 3.1.4 on 2021-01-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0012_auto_20210103_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='boolanswer',
            name='form_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myform.form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqanswer',
            name='form_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myform.form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanswer',
            name='form_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myform.form'),
            preserve_default=False,
        ),
    ]
